name: Sync to Organization Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Push to Organization Repo
      run: |
        git config --global user.name 'ncborcherding'
        git config --global user.email 'ncborch@gmail.com'
        git remote add org https://x-access-token:${{ secrets.ORG_PAT }}@github.com/BorchLab/scRepertoire.git'
        git push org_repo master --force --verbose 
