# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      # This step is changed to generate the cobertura.xml file
      - name: Test coverage and generate report
        run: |
          covr::cobertura(
            quiet = FALSE,
            clean = FALSE,
            exclusions = "R/global.R",
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"),
            file = "cobertura.xml"
          )
        shell: Rscript {0}

      - uses: codecov/codecov-action@v4
        with:
          # This token is usually not required for public repositories on GitHub Actions
          # token: ${{ secrets.CODECOV }} 
          fail_ci_if_error: ${{ github.event_name != 'pull_request' }}
          file: ./cobertura.xml
          # The 'noop' plugin is not needed when you are uploading a report file
          # plugin: noop 
          disable_search: true
          
      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
